MSIT158_2_FinalProject/Controllers/ValuableCustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MSIT158_2_FinalProject.Models;

namespace MSIT158_2_FinalProject.Controllers
{
    public class ValuableCustomerController : Controller
    {
        private readonly SelectShopContext _context;
        public ValuableCustomerController(SelectShopContext context)
        {
            _context = context;
        }
        public IActionResult List()
        {
            IEnumerable<TVip> datas = null;
            datas = from v in _context.TVips
                    select v;
            return View(datas);
        }
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("List");
            TVip r = _context.TVips.FirstOrDefault(x => x.Vipid == id);
            if (r == null)
                return RedirectToAction("List");
            return View(r);
        }
        [HttpPost]
        public IActionResult Edit(TVip vipIn, IFormFile avatar)
        {
            if(avatar == null)
                return RedirectToAction("List");

            //檔案上傳轉成二進位
            byte[] imgByte = null;
            using (var memoryStream = new MemoryStream())
            {
                avatar.CopyTo(memoryStream);
                imgByte = memoryStream.ToArray();
            }
            TVip vipDb = _context.TVips.FirstOrDefault(x => x.Vipid == vipIn.Vipid);
            if (vipDb != null)
            {
                vipDb.Vipname = vipIn.Vipname;
                vipDb.Vipphoto = imgByte;
                _context.SaveChanges();
            }
            return RedirectToAction("List");
        }
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                //TVip r = _context.TVips.FirstOrDefault(x => x.Vipid == id);
                //if (r != null)
                //{
                //    _context.TVips.Remove(r);
                //    _context.SaveChanges();
                //}
            }
            return RedirectToAction("List");
        }
    }
}

MSIT158_2_FinalProject/Views/ValuableCustomer/Edit.cshtml
@model MSIT158_2_FinalProject.Models.TVip

@{
    ViewData["Title"] = "Edit";
    Layout = "_Layout_Backstage";
}

<h1>修改資料</h1>

<h4>填寫資訊</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Vipid" class="control-label"></label>
                <input asp-for="Vipid" class="form-control" />
                <span asp-validation-for="Vipid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vipname" class="control-label"></label>
                <input asp-for="Vipname" class="form-control" />
                <span asp-validation-for="Vipname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <img style="height: 200px; object-fit: contain;" src="@(Model.Vipphoto != null ? "data:image/jpeg;base64," + Convert.ToBase64String(Model.Vipphoto) : "")" alt="等級照片" /><br />
                <label asp-for="Vipphoto" class="control-label"></label>
                <input asp-for="Vipphoto" class="form-control" id="InputVipPhoto" name="avatar" type="file" />
                <span asp-validation-for="Vipphoto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="存檔並送出" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <button type="button" class="btn btn-light"><a asp-action="List">返回</a></button>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MSIT158_2_FinalProject/Views/ValuableCustomer/List.cshtml
@model IEnumerable<MSIT158_2_FinalProject.Models.TVip>

@{
    ViewData["Title"] = "List";
    Layout = "_Layout_Backstage";
}

<h1>會員等級資料一覽表</h1>
<div id="pimg">
    
</div>
<p>
    <button type="button" class="btn btn-light"><a asp-action="Create">新增資料</a></button>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Vipid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vipname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vipphoto)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Vipid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vipname)
            </td>
            <td>
                <img style="width: 100px; object-fit: contain;" src="@(item.Vipphoto != null ? "data:image/jpeg;base64," + Convert.ToBase64String(item.Vipphoto) : "")" alt="等級照片" /><br />
                @* @Html.DisplayFor(modelItem => item.Vipphoto) *@
            </td>
            <td>
                @Html.ActionLink("修改", "Edit", "ValuableCustomer", new { id = item.Vipid },  new {@class="btn btn-success"}) |
                @* @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) | *@
                @Html.ActionLink("刪除", "Delete", "ValuableCustomer", new { id = item.Vipid }, new { onclick = "return confirm('確定要刪除嗎?')" ,@class="btn btn-danger"})
            </td>
        </tr>
}
    </tbody>
</table>
@section Styles {
    <style>
        .vertical-group {
            display: flex;
            flex-direction: column;
            align-items: center; /* 確保垂直群組的項目水平置中 */
            gap: 20px; /* 調整間距 */
            width: 100%; /* 確保群組佔滿整個寬度 */
        }

        .horizontal-group {
            display: flex;
            flex-direction: row;
            justify-content: center; /* 確保旋轉木馬水平置中 */
            align-items: stretch; /* 伸展項目以填滿容器 */
            gap: 20px; /* 調整間距 */           
            margin: 10px 250px; /* 左右各250px的間距 */
            width: 50%; /* 確保群組佔滿50%的寬度 */
        }

        .custom-carousel {
            flex: 1; /* 確保旋轉木馬佔據可用空間 */
            width: 30%;
            margin: auto; /* 使旋轉木馬居中 */
        }
    </style>
}

@section Scripts {
    <script>
        document.querySelector('#pimg').innerHTML = `
                    <div class="horizontal-group">
                        <div id="carouselExampleInterval1" class="carousel slide custom-carousel" data-bs-ride="carousel">
                            <div class="carousel-indicators">
                                <button type="button" data-bs-target="#carouselExampleInterval1" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                                <button type="button" data-bs-target="#carouselExampleInterval1" data-bs-slide-to="1" aria-label="Slide 2"></button>
                                <button type="button" data-bs-target="#carouselExampleInterval1" data-bs-slide-to="2" aria-label="Slide 3"></button>
                                <button type="button" data-bs-target="#carouselExampleInterval1" data-bs-slide-to="3" aria-label="Slide 4"></button>
                            </div>
                            <div class="carousel-inner">
                                <div class="carousel-item active" data-bs-interval="1000">
                                    <img src="@Url.Content("~/img/sdesigner (1).jpeg")" class="d-block w-100" alt="...">
                                </div>
                                <div class="carousel-item" data-bs-interval="1000">
                                    <img src="@Url.Content("~/img/sdesigner (2).jpeg")" class="d-block w-100" alt="...">
                                </div>
                                <div class="carousel-item" data-bs-interval="1000">
                                    <img src="@Url.Content("~/img/sdesigner (3).jpeg")" class="d-block w-100" alt="...">
                                </div>
                                <div class="carousel-item" data-bs-interval="1000">
                                    <img src="@Url.Content("~/img/sdesigner (4).jpeg")" class="d-block w-100" alt="...">
                                </div>
                            </div>
                        </div>
                        <div id="carouselExampleInterval2" class="carousel slide custom-carousel" data-bs-ride="carousel">
                            <div class="carousel-indicators">
                                <button type="button" data-bs-target="#carouselExampleInterval2" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                                <button type="button" data-bs-target="#carouselExampleInterval2" data-bs-slide-to="1" aria-label="Slide 2"></button>
                                <button type="button" data-bs-target="#carouselExampleInterval2" data-bs-slide-to="2" aria-label="Slide 3"></button>
                                <button type="button" data-bs-target="#carouselExampleInterval2" data-bs-slide-to="3" aria-label="Slide 4"></button>
                            </div>
                            <div class="carousel-inner">
                                <div class="carousel-item active" data-bs-interval="1000">
                                    <img src="@Url.Content("~/img/sdesigner (5).jpeg")" class="d-block w-100" alt="...">
                                </div>
                                <div class="carousel-item" data-bs-interval="1000">
                                    <img src="@Url.Content("~/img/sdesigner (6).jpeg")" class="d-block w-100" alt="...">
                                </div>
                                <div class="carousel-item" data-bs-interval="1000">
                                    <img src="@Url.Content("~/img/sdesigner (7).jpeg")" class="d-block w-100" alt="...">
                                </div>
                                <div class="carousel-item" data-bs-interval="1000">
                                    <img src="@Url.Content("~/img/sdesigner (8).jpeg")" class="d-block w-100" alt="...">
                                </div>
                            </div>
                        </div>
                    </div>`;
    </script>
}